[project]
name = "machine-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "common_project @ file:///${PROJECT_ROOT}/../common_project",
    "redis"
]

